### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by baigang666** [TencentYoutuResearch/SceneSegmentation-SCRL#1]
Dear author:
Thanks for contributing an insightful work and make it published! it's helpful!
please When will the code be open source?
thank you

**Comment by LinusWu** [comment]
Hi baigang666,

Thanks for the attention to our work.
The plan to open source code is in the internal process, and the code and model weight will be released soon.

Best,
Haoqian Wu

**Comment by baigang666** [comment]
> Hi baigang666,
> 
> Thanks for the attention to our work. The plan to open source code is in the internal process, and the code and model weight will be released soon.
> 
> Best, Haoqian Wu

Listen the message,I very exciting.

**Comment by chenbinghui1** [comment]
So, when will the code be available.

**Comment by dengbuqi** [comment]
> So, when will the code be available.

+1 @baigang666

**Comment by YOONSEOKHEO** [comment]
Dear @LinusWu 

Hi, I am very glad to know about your impressive work. 
I am hoping to know the time for the code release. 

Best. 
Yoonseok Heo.

**Comment by LinusWu** [comment]
> YOONSEOKHEO

Hi Yoonseok,

We have handed over the code to the company's open source team early.

It is currently in the Code Review process.

I believe the code will be uploaded to GitHub soon.

Best,
Haoqian Wu.

**Comment by LinusWu** [comment]
The code and checkpoints are available now.
