### ISSUE TITLE
Problems with inference BiLSTM

### ISSUE THREAD

**Issue by Dokholyan** [TencentYoutuResearch/SceneSegmentation-SCRL#10]
Thank you very much for your work!
I'm having problems running biLSTM, all predicted probabilities are very small and as a result the quality is f_score = 0. Could you please tell me what I'm doing wrong?

`
import torch

from SceneSeg.movienet_seg_data import MovieNet_SceneSeg_Dataset_Embeddings_Val
from SceneSeg.BiLSTM_protocol import BiLSTM

emb_dataset = MovieNet_SceneSeg_Dataset_Embeddings_Val(
    pkl_path='/home/vsdoholyan/scene_segmentation/SceneSegmentation-SCRL/test.pkl',
    sampled_shot_num=40)

scene_detection_model = BiLSTM()
scene_detection_weights = torch.load('./../SceneSegmentation-SCRL/checkpoints/checkpoint.pth.tar')['state_dict']
scene_detection_model.load_state_dict(scene_detection_weights, strict=True)
scene_detection_model.eval();

inference(scene_detection_model, test_loader)

(0.0, 0.1441130085764919, 0.9234638031252359)
`

**Comment by rabachi** [comment]
I'm having the same problem when running it on a custom file but it works fine on Movienet. Did you resolve it?

**Comment by LinusWu** [comment]
I'm not quite sure what problem you met, based on the code fragments.
You can try to solve the problem according to the following:
1. set batch size of `test_loader` to 1
2. init model with default setting: https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/blob/main/SceneSeg/main.py#L19
3. fill the argument `args` (in https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/blob/main/SceneSeg/main.py#L108) with default setting
4. check your torch version, please see this [issue](https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/issues/6#issuecomment-1538015851)
