### ISSUE TITLE
Using Audio modality

### ISSUE THREAD

**Issue by rabachi** [TencentYoutuResearch/SceneSegmentation-SCRL#11]
It is mentioned in the paper that audio is also used for training but it seems this code does not include any audio processing, is that correct? For example, if I have a custom set of keyframes and an audio file (.wav), I can use extract_embeddings.py to get the embeddings for the shots but how can I also get embeddings for the audio? Do you use a pretrained audio encoder from LGSS?

**Comment by 980044579** [comment]
Code does not include any audio processing~

**Comment by LinusWu** [comment]
Yes, we didn't provide any code for audio processing. One of the important reasons is: MoiveNet has no complete audio data, and involving its incomplete audio data/embeddings can lead to performance degradation. A similar phenomenon has been observed by others recently (https://arxiv.org/abs/2308.11185, see Sec. 4.5). 

Technically, we tried both audio encoder from LGSS  and  Cnn14 encoder on the MovieNet, but led to the same conclusion.

If you want to try this algorithm on the other dataset, any reasonable audio encoder can be applied to the SSL pipeline.

**Comment by rabachi** [comment]
Thanks so much for your helpful response @LinusWu!
