### ISSUE TITLE
关于scene318 标签

### ISSUE THREAD

**Issue by babyta** [TencentYoutuResearch/SceneSegmentation-SCRL#14]
label318 里面
0000 0
0001 0
0002 0
0003 1
0004 -1
0005 -1
0006 0
0007 1
0008 0
这个 0 1 -1代表啥意思呀

**Comment by LinusWu** [comment]
please refer to this issue: 
https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/issues/4#issuecomment-1525091262

**Comment by babyta** [comment]
thanks
