### ISSUE TITLE
 How to apply this brilliant work to my own videos?

### ISSUE THREAD

**Issue by huangyuhui666** [TencentYoutuResearch/SceneSegmentation-SCRL#3]
Hi, 
thank you for such a wonderful work. 
While studying your work, I have encountered some problems and would like to ask for your help. 
How should I apply the pre-trained model to my own videos?
Best Wishes~

**Comment by LinusWu** [comment]
Hi @huangyuhui666,
If you plan to use our pre-trained model to finetune on your own videos, you can follow these steps:
1. Use the shot segmentation/detection algorithm (e.g., [movienet-tools](https://github.com/movienet/movienet-tools) or [TransNetV2](https://github.com/soCzech/TransNetV2)) to find the frame number of the shot change in the video.
2. Sample 3 frames of images for all shots.
3. Modify the dataloader to fit your dataset (or make puzzles for pre-training, see README)

**Comment by 980044579** [comment]
I would like to ask you what is the strategy for selecting three frames for each shot, is it random sampling or uniform sampling or other？

**Comment by LinusWu** [comment]
@980044579 
In MovieNet dataset, it only provides three frames for each shot, and their strategy is presented in [the source code](https://github.com/movienet/movienet-tools/blob/master/movienet/tools/shotdetect/shotdetect/keyf_img_saver.py#L100).

In short, three frames of a single shot are the starting, middle and ending frames, respectively.

**Comment by 980044579** [comment]
Thank you so much for your quick reply, got it
