### ISSUE TITLE
What means params in "movie1K.scene_seg_318_name_index_shotnum_label.v1.json"

### ISSUE THREAD

**Issue by MrCorsair3** [TencentYoutuResearch/SceneSegmentation-SCRL#4]
Hello,
thanks for great article and project.
I am currently testing it. I wonder what the numbers 0, 1 and -1 in the movie1K.scene_seg_318_name_index_shotnum_label.v1.json file means. If I good understand they are assigned to every frame from every shot.

Thanks for your help and best regards

**Comment by LinusWu** [comment]
@MrCorsair3 
0, 1 and -1 are the scene segmentation labels, indicate whether the current shot and the next shot belong to the same scene, "0" stands for "the same scene" and vice versa. BTW, "-1" means uncertain, and is processed as "1" accroding to the related [benchmark](https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/blob/main/extract_embeddings.py#L47).

**Comment by MrCorsair3** [comment]
Great, thank you very much
