### ISSUE TITLE
Scene grouping

### ISSUE THREAD

**Issue by MrCorsair3** [TencentYoutuResearch/SceneSegmentation-SCRL#5]
Thank you for the code and very good work.

I have a question, does this method group similar scenes or just mark the places where the scene changes?
There is an "inference" method in main.py, but it doesn't have a clustering method. On the other hand, there is a "cluster" directory in the project, can this be done with it?

Best regards

**Comment by LinusWu** [comment]
Hi @MrCorsair3,
The grouping/clustering strategy is only used in the pre-training stage, to find similar shots in a training batch without supervision, and often these shots are likely to belong to a scene. 
Technically, the clustering method is implemented in  [cluster/Group.py](https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/blob/main/cluster/Group.py) and performed in the [models/core/SCRL_MoCo.py](https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/blob/main/models/core/SCRL_MoCo.py).

**Comment by MrCorsair3** [comment]
Many thanks for the answer @LinusWu .
can i use your algorithm to divide the movie into scenes and then group them together with similar scenes?
It seems to me that in its current form the algorithm is intended for finding places (shots) where the scene changes, am I right? (I'm using the test_dataset and the inference method from SceneSeg/main.py)

**Comment by LinusWu** [comment]
- So far, this algorithm only supports finding scene change positions from a long sequence of shots (Yes, you are right).
- If you want to find more similar scenes, you can utilize unsupervised algorithms (such as clustering) to find them. 
- Further, movie scene taxonomy is an open-set problem, and scenes could hardly be classified into fixed categories.

**Comment by MrCorsair3** [comment]
Thanks for your answer. 
Regards, and I wish you success in your future work.
