### ISSUE TITLE
model in STEP 2 Embeddings  damaged

### ISSUE THREAD

**Issue by 980044579** [TencentYoutuResearch/SceneSegmentation-SCRL#6]
Many thanks to you for  flawless work. I'm sorry that can you check the model file in STEP 2 Embeddings you provided can't be decompressed？

Best wish.

**Comment by LinusWu** [comment]
Hi @980044579,

I'm not very sure which file is broken, but you can try to load the embeddings in this way:
```python
import pickle
pick_path = './val.pkl'
with open(pick_path, 'rb') as f:
    data = pickle.load(f)
print(len(data.keys()))
print(list(data.keys())[0])
print(len(data['tt0048545']))
# Output:
# 64
# tt0048545
# 836
```

**Comment by 980044579** [comment]
I'm sorry for my mistake, I mean chekpoint in [STEP 1 Pre-training](https://drive.google.com/drive/folders/1ZYg9PFRU_lt3G5qJrldkguA52T2oxErR)， I downloaded it, but there was an error in decompression

**Comment by LinusWu** [comment]
> I'm sorry for my mistake, I mean chekpoint in [STEP 1 Pre-training](https://drive.google.com/drive/folders/1ZYg9PFRU_lt3G5qJrldkguA52T2oxErR)， I downloaded it, but there was an error in decompression

I redownload the checkpoint you gave, and the model parameters can be loaded normally using [extracting code](https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/blob/main/extract_embeddings.py#L88): 
```python
import torch
weight_path = './checkpoint_0099.pth.tar'
model_weight = torch.load(weight_path,map_location=torch.device('cpu'))['state_dict']
print(len(model_weight.keys())) # 646
```
The above code can run normally in torch 1.6 and 2.0, please check your environment or loading code again.

Best,

**Comment by 980044579** [comment]
After upgrading the torch version, the model can be loaded normally.Thanks
