### ISSUE TITLE
How can we test the algorithm in our own videos?

### ISSUE THREAD

**Issue by ytddd75** [TencentYoutuResearch/SceneSegmentation-SCRL#7]
Hi, thanks for your excellent work. 
We do not plan to fine-tune the model for the time being. How can we test the algorithm in our own video using the checkpoints you provided and output the segmented video clip?
Best wishes.

**Comment by 980044579** [comment]
1.Get shot segmentation （transnetv2）
2.Generate emmbedding pkl files
3.Inference

**Comment by LinusWu** [comment]
Thanks to the instructions from @980044579.
Technically, shot information is required first, both transnetv2 and [movienet-tool](https://github.com/movienet/movienet-tools) can be directly performed to get the beginning and ending frame indexs for a specific shot. Then, you can sample three frames from one shot in the video, feeding to the pretrained encoder to get embeddings.

**Comment by LinusWu** [comment]
> Thanks to the instructions from @980044579. Technically, shot information is required first, both transnetv2 and [movienet-tool](https://github.com/movienet/movienet-tools) can be directly performed to get the beginning and ending frame indexs for a specific shot. Then, you can sample three frames from one shot in the video, feeding to the pretrained encoder to get embeddings.

Also can refer to [issue3](https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/issues/3#issuecomment-1537082603)

**Comment by babyta** [comment]
> 1.Get shot segmentation （transnetv2） 2.Generate emmbedding pkl files 3.Inference

Hello, where is the inference code?
