### ISSUE TITLE
pretrained ckpt error

### ISSUE THREAD

**Issue by ZutongLi** [TencentYoutuResearch/SceneSegmentation-SCRL#8]
Hi there, 

Thanks for sharing this amazing work. I found the step 1 ckpt for "w/ ImageNet-1k" contains some error, when I invoke tar command. it seems the tar file is broken. Would you mind check the file? Thanks

**Comment by JellyDream** [comment]
After my practice, there is no error in the model file of step 1, you can try again according to the code and the corresponding error.
经过我的实践，步骤1的模型文件并没有错误，你可以根据代码和相应的错误再试一次。

**Comment by ZutongLi** [comment]
Thanks for the quick response, I used two machines and downloaded a total of three times. Unfortunately, I couldn't extract any of the three files. There was an error stating that the tar package is problematic. May I ask if you were checking the file (checkpoint_0099.pth.tar ) on Google Drive?
感谢快速回复， 我在两台机器上一共下载了三次， 每次解压的时候，都是报错tar包损坏。请问您检查的是Google drive  "w/ ImageNet-1k" 版本的 checkpoint_0099.pth.tar 文件吗

**Comment by JellyDream** [comment]
已收到!

**Comment by LinusWu** [comment]
> Hi there,
> 
> Thanks for sharing this amazing work. I found the step 1 ckpt for "w/ ImageNet-1k" contains some error, when I invoke tar command. it seems the tar file is broken. Would you mind check the file? Thanks

Hi,

Please update your PyTorch, or refer to this [issue](https://github.com/TencentYoutuResearch/SceneSegmentation-SCRL/issues/6#issuecomment-1538015851)

**Comment by ZutongLi** [comment]
Cool, it is not a tar file. I can directly load it by torch. Thanks, the issue fixed.
