### ISSUE TITLE
Missing Key in Feature Extractor

### ISSUE THREAD

**Issue by ZutongLi** [TencentYoutuResearch/SceneSegmentation-SCRL#9]
Hi when I invoke the feature extractor of step 1, I found the error from function "get_encoder" (extract_embeddings.py)
"_IncompatibleKeys(missing_keys=['fc.weight', 'fc.bias'], unexpected_keys=['module.encoder_q.fc.0.weight', 'module.encoder_q.fc.0.bias', 'module.encoder_q.fc.2.weight', 'module.encoder_q.fc.2.bias'])"

seems the ckpt of step 1 is error. (w/ ImageNet-1k version). 
I invoke twice feature extractor, and returned differnt embeddings. 

您好，我在第一步提取特征的时候，发现pth文件好像有些key和resnet50对不上，以上是报错信息。

**Comment by babyta** [comment]
n你好加载这块怎么解决呀，我用的高版本torch，出现各种问题

**Comment by babyta** [comment]
model_weight = torch.load(weight_path, map_location=torch.device('cpu'))['state_dict']
KeyError: 'state_dict'

**Comment by KarineAyrs** [comment]
I have the same issue with KeyError: 'state_dict'
